AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ArsenPdp EC2 SSH Bastion

Parameters:
  SSHKeyName:
    Type: String
  InstanceType:
    Type: String
  BastionSecurityGroupId:
    Type: String
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  ImageId:
    Description: The ID of the AMI. An AMI ID is required to launch an instance and must be specified here or in a launch template.
    Type: String
  ProjectName:
    Type: String
  EnvTag:
    Type: String

Resources:
  ArsenPdpBastionInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  ArsenPdpBastionInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ArsenPdpBastionInstanceRole

  ArsenPdpBastionLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      LaunchConfigurationName: ArsenPdpBastionLaunchConfig
      AssociatePublicIpAddress: true
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref SSHKeyName
      SecurityGroups:
        - !Ref BastionSecurityGroupId

  ArsenPdpBastionASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ArsenPdpBastionAutoScalingGroup
      LaunchConfigurationName: !Ref ArsenPdpBastionLaunchConfig
      VPCZoneIdentifier: !Ref PublicSubnets
      MinSize: "1"
      DesiredCapacity: "1"
      MaxSize: "1"
      Tags:
        - Key: Name
          Value: ArsenPdpBastionAutoScalingGroup
          PropagateAtLaunch: true
        - Key: project
          Value: !Ref ProjectName
          PropagateAtLaunch: true
        - Key: env
          Value: !Ref EnvTag
          PropagateAtLaunch: true

  ArsenPdpBastionSSHInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref SSHKeyName
      IamInstanceProfile: !Ref ArsenPdpBastionInstanceProfile
      SecurityGroupIds:
        - !Ref BastionSecurityGroupId
      SubnetId: !Select [0, !Ref PublicSubnets] # Public A
      UserData: !Base64 |
        #!/bin/bash
        sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
        sudo systemctl status amazon-ssm-agent
      Tags:
        - Key: Name
          Value: ArsenPdpBastionSSHInstance
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref EnvTag
