AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ArsenPdp Security

Parameters:
  ProjectName:
    Type: String
  VPC:
    Type: AWS::EC2::VPC::Id
  EnvTag:
    Type: String

Resources:
  ArsenPdpLambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Lambda Functions
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: ArsenPdpLambdaSecurityGroup
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref EnvTag

  ArsenPdpSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ArsenPdp server security group.
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          Description: http
          SourceSecurityGroupId: !Ref ArsenPdpLambdaSecurityGroup
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          Description: https
          SourceSecurityGroupId: !Ref ArsenPdpLambdaSecurityGroup
      Tags:
        - Key: Name
          Value: ArsenPdpSecurityGroup
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref EnvTag

  ArsenPdpDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Ingress for DB
      SecurityGroupIngress:
        - IpProtocol: tcp
          Description: "Private Subnet A"
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.100.11.0/24
        - IpProtocol: tcp
          Description: "Private Subnet B"
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.100.21.0/24
        - IpProtocol: tcp
          Description: "Public Subnet A"
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.100.10.0/24
      Tags:
        - Key: Name
          Value: ArsenPdpDBSecurityGroup
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref EnvTag

Outputs:
  ArsenPdpSecurityGroup:
    Description: "ArsenPdp Main Security group"
    Value: !GetAtt ArsenPdpSecurityGroup.GroupId
  ArsenPdpDbSecurityGroupId:
    Description: "ArsenPdp DB Security group"
    Value: !GetAtt ArsenPdpDBSecurityGroup.GroupId
  ArsenPdpLambdaSecurityGroup:
    Description: "ArsenPdp Lambda Security group"
    Value: !GetAtt ArsenPdpLambdaSecurityGroup.GroupId
    Export:
      Name: ArsenPdpLambdaSecurityGroup
