AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ArsenPdp Infrastructure

Mappings:
  DbParametersMap:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: ../parameters/db-parameters.yaml
  ParametersMap:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: ../parameters/parameters.yaml

Parameters:
  HVMLinux2:
    Type: String
    Default: ami-0443305dabd4be2bc
  ProjectName:
    Type: String
    Default: ArsenPdp
  EnvironmentName:
    Type: String
    AllowedValues:
      - Dev
      - Prod
    Default: Dev

Resources:
  ArsenPdpCloud:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/cloud.yaml
      Parameters:
        EnvTag: !FindInMap [ParametersMap, !Ref EnvironmentName, EnvTag]
        ProjectName: !Ref ProjectName

  ArsenPdpSecurity:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/security.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        VPC: !GetAtt ArsenPdpCloud.Outputs.ArsenPdpVPC
        EnvTag: !FindInMap [ParametersMap, !Ref EnvironmentName, EnvTag]

  ArsenPdpDatabase:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/database.yaml
      Parameters:
        DbName: !FindInMap [DbParametersMap, Common, Name]
        DbUserName: !FindInMap [DbParametersMap, !Ref EnvironmentName, UserName]
        DbPassword: !FindInMap [DbParametersMap, !Ref EnvironmentName, Password]
        DbSecurityGroupId: !GetAtt ArsenPdpSecurity.Outputs.ArsenPdpDbSecurityGroupId
        PrivateSubnets: !GetAtt ArsenPdpCloud.Outputs.PrivateSubnets
        EnvTag: !FindInMap [ParametersMap, !Ref EnvironmentName, EnvTag]
        ProjectName: !Ref ProjectName
        StorageSize: !FindInMap [DbParametersMap, !Ref EnvironmentName, StorageSize]
        StorageType: !FindInMap [DbParametersMap, !Ref EnvironmentName, StorageType]
        InstanceClass: !FindInMap [DbParametersMap, !Ref EnvironmentName, InstanceClass]
        Engine: !FindInMap [DbParametersMap, Common, Engine]
        EngineVersion: !FindInMap [DbParametersMap, Common, EngineVersion]
        EnvironmentName: !Ref EnvironmentName

  ArsenPdpInstanceBackendMain:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/ec2-main.yaml
      Parameters:
        SSHKeyName: !FindInMap [ParametersMap, !Ref EnvironmentName, SSHKeyName]
        NodeInstanceType: !FindInMap [ParametersMap, !Ref EnvironmentName, ServerEC2InstanceType]
        MainServerSecurityGroupId: !GetAtt ArsenPdpSecurity.Outputs.ArsenPdpSecurityGroup
        SubnetIds: !GetAtt ArsenPdpCloud.Outputs.PrivateSubnets
        ImageId: !Ref HVMLinux2
        EnvTag: !FindInMap [ParametersMap, !Ref EnvironmentName, EnvTag]
        ProjectName: !Ref ProjectName

  ArsenPdpInstanceBastion:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/ec2-main.yaml
      Parameters:
        SSHKeyName: !FindInMap [ParametersMap, !Ref EnvironmentName, SSHKeyName]
        InstanceType: !FindInMap [ParametersMap, !Ref EnvironmentName, ServerEC2InstanceType]
        BastionSecurityGroupId: !GetAtt ArsenPdpSecurity.Outputs.ArsenPdpBastionSecurityGroup
        SubnetIds: !GetAtt ArsenPdpCloud.Outputs.PublicSubnets
        ImageId: !Ref HVMLinux2
        EnvTag: !FindInMap [ParametersMap, !Ref EnvironmentName, EnvTag]
        ProjectName: !Ref ProjectName

  ArsenPdpAPIGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  ArsenPdpAPIGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ArsenPdpAPIGatewayRole.Arn

  ArsenPdpLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
      Policies:
        - PolicyName: ArsenPdpParametersAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ArsenPdp*"

Outputs:
  ArsenPdpLambdaRole:
    Description: "ArsenPdp Lambda Role"
    Value: !GetAtt ArsenPdpLambdaRole.Arn
    Export:
      Name: ArsenPdpLambdaRole
